### ISSUE TITLE
[FR] The container in which the food is located, and the amount (or weight) of the food

### ISSUE THREAD

**Issue by MageDelfador** [NielsLee/FoodRecords#19]
感谢作者开发了一个如此实用的APP，实际体验了一下发现还需要这样几个功能。
- 存放食物的地方可能会有好几个，比如多个冰箱、各种橱柜。所以需要分类显示的功能，比如我想知道单独某个冰箱里还有什么。容器分类也可以精确一些比如冰箱的第几层。
- 食品的数量或重量也需要设置和显示，比如6个橙子，一箱牛奶，2斤小米，每次取用不会全部取走，只用备注的话会很不方便。

如果可以的话最好再加上下面这两个功能(如果能实现的话)

- 为系统自带的日历添加事件(或其他方法)，防止APP提醒不及时。
- 多人数据同步，每人一个APP，共享和同步数据

**Comment by je-sendra** [comment]
Translated (auto) issue for convenience:

Thanks to the author for the development of a so-called APP, which was actually identified as requiring several functions.

There may be a number of places where food is stored, such as multiple refrigerators and various dressings. It is therefore necessary to classify the functions indicated, for example, what I would like to know separately in a ice box. The classification of containers may also precision a number of such ice boxes.
The quantity or weight of food will also need to be established and shown, for example, six oranges, one box cattle, 2 minor miles, each being taken without full access, and it would not be convenient only if they are available.
If so, it would be preferable to add the two functions (if achievable) below.

The addition of events (or other methods) to the system's own calendar is not timely.
Multiple data are synchronized and each individual APP shared and synchronized data.

**Comment by je-sendra** [comment]
I had the same problem, since I wanted to know how many eggs I had

I might be able to fix this issue myself somewhere around next week.

I will make a pull request with my changes.

Happy coding!

**Comment by NielsLee** [comment]
❤Thanks for your comments~ 
Regarding the quantity, there are many people who have raised this demand, so I think this is a feature that must be realized; As for how to realize it, since I hope the APP can reduce the workload of entering information as much as possible, I think it is possible to enter only the "quantity" without inputting the explicit "unit"."quantity".For example, if the number of eggs is 5, then it means 5 eggs; if the number of milk is 3, then it means 3 cartons of milk, and if the number of beef is 2, then it means 2 pieces of beef; this way, even though the statistics are not very accurate, it's still better than having to input too much information that causes people to be lazy to use it; In addition, I learned about an interesting idea from the app of [epholys@gmail.com] (mailto:epholys@gmail.com) has an interesting idea: he provides two options in his app: "Eat" and "Throw away".Eat" means to delete the food at once, and "Eat" means to reduce the food one by one; I think this idea is much more vivid than my "Delete".
@je-sendra What do you think of this idea? Or you can also share yours


❤感谢各位提出的意见~
关于数量，已经有很多人提出这个需求了，所以我觉得这是一个一定要实现的功能；
至于如何实现，由于我希望APP能够尽可能地减轻录入信息时候的工作量，所以我认为可以不输入明确的“单位”，仅仅输入“数量”。比如说鸡蛋的数量是5，那么它就表示5个鸡蛋；牛奶的数量是3，那么它就表示3盒牛奶，牛肉的数量是2，那么它就表示2块牛肉；这样虽然统计的不是很精准，但是比起要输入太多的信息导致大家懒得去用，还是要好一些的；
另外，我之前从 [epholys@gmail.com](mailto:epholys@gmail.com) 的APP里了解到一个很有意思的想法：他在他的APP中提供了“吃掉”和“丢掉”两种选项；“丢掉”表示将吃的一次性删除，“吃掉“表示一份一份地减少；我觉得这个思路比我的”删除“要生动的多。
@je-sendra 你觉得这个思路咋样？或者你也可以分享一下你的思路？

**Comment by MageDelfador** [comment]
我认为添加一个单位的选项并不会增加录入操作的复杂度。每个人的需求不同，如果觉得这样界面会看起来比较复杂，可以添加类似“更多选项”的按钮。
从减少操作步骤的角度考虑，不如添加一个扫描商品条形码直接录入的功能。

**Comment by MageDelfador** [comment]
可以在这里查询到商品条形码信息
https://www.gds.org.cn/

**Comment by je-sendra** [comment]
> 可以在这里查询到商品条形码信息
> https://www.gds.org.cn/

that webpage only works for china products, sadly

Regarding the barcode functionality, I think that it should be separated into a different issue, since it is out of the scope of the original problem presented in this issue, being the capability of adding the amount of a product.

However, I think the barcode functionality might be nice anyway (even if not connected to the China products database) to be able to quickly open an "actions" menu for the product (like eat, throw away or add more stock).

Please do not connect to the China product database since that would add an external cloud dependency (non-free) and thus the app would not comply with libre software standards.

I think the "Eat" and "Throw away" idea is good.

------------------------------------------------
> 可以在这里查询到商品条形码信息
> https://www.gds.org.cn/

遗憾的是，该网页仅适用于中国产品

关于条形码功能，我认为应该将其分为另一个问题，因为它超出了本问题中提出的原始问题的范围，即添加产品数量的能力。

但是，我认为条形码功能可能无论如何都很好（即使没有连接到中国产品数据库），能够快速打开产品的“操作”菜单（如食用、扔掉或添加更多库存）。

请不要连接到中国产品数据库，因为这会增加外部云依赖项（非免费），因此该应用程序不符合自由软件标准。

我认为“食用”和“扔掉”的想法很好。

**Comment by Modificator** [comment]
> 可以在这里查询到商品条形码信息
也许，手动绑定条形码码和物品比较好，在物品编辑界面添加扫码绑定条形码功能
或者，使用 OpenAI CLIP 之类的图像识别物品

**Comment by NielsLee** [comment]
https://github.com/NielsLee/FoodRecords/releases/tag/v1.8

**Comment by Eyion** [comment]
还是觉得自行设置单位更为实用，按照举例中，鸡蛋的单位用“个”问题不大，但牛奶数量3，如果默认是3箱，这样局限性很大，因为牛奶可能是3瓶，每瓶250ml
