### ISSUE TITLE
[FR] Please add ways to customize the date format

### ISSUE THREAD

**Issue by meyou69** [NielsLee/FoodRecords#24]
Hello,

I wish to request the implementation of a setting with which the user can tweak the date format shown in the app.

I'm from Romania, where the date format is usually DD.MM.YYYY. The current date format used in the app seems to be YY-MM-DD, which is very confusing to me, as it always misleads me to thinking that the "24" part at the beginning refers to the day of the month, rather than what it actually is, which is the year.

Being able to tweak the format would be very beneficial, preferably allowing the user to specify their own character separator for the elements, and also being able to specify the order of the elements, as well as even letting them choose between the short version of showing the year compared to the long version (i.e. "24" vs "2024").

At a minimum, if these are too much, I'd like to request at least a choice picker that would allow to switch between the current date format and the Romanian one

**Comment by NielsLee** [comment]
Hi!
It’s a very useful suggestion. Since I never been to Europe, it’s a little difficult for me to consider the different usage habits there without others' feedback;  I will implement it in the coming version, thank you for making Fridgey much easier to use!



Hello,

I wish to request the imolementation of a setting with which the user can tweak the date format shown in the app.

I'm from Romania, where the date format is usually DD.MM.YYYY. The current date format used in the app seems to be YY-MM-DD, which is very confusing to me, as it always misleads me to thinking that the "24" part at the beginning refers to the day of the month, rather than what it actually is, which is the year.

Being able to tweak the format would be very beneficial, preferably allowing the user to specify their own character separator for the elements, and also being able to specify the order of the elements, as well as even letting them choose between the short version of showing the year compared to the long version (I.e. "24" vs "2024").

At a minimum, if these are too much, I'd like to request at least a choice picker that would allow to switch between the current date format and the Romanian one

**Comment by NielsLee** [comment]
https://github.com/NielsLee/FoodRecords/releases/tag/v1.6
